# Site settings
title:  Surrey Stairs
email: sales@surreystairs.co.uk
telephone: 01483 418545
fax: 01483 431967
mobile: 07778 762190
description: "Surrey Stairs"
baseurl: ""
url: "http://surreystairs.co.uk"

# Build settings
markdown: redcarpet
permalink: pretty
exclude : ['vendor', 'Gemfile*', 'bin', 'README.md']
